# Generated by Django 4.0.3 on 2024-01-09 11:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_alter_contact_created_alter_rate_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 11, 53, 28, 765247, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rate',
            name='created',
            field=models.TimeField(default=datetime.datetime(2024, 1, 9, 11, 53, 28, 770251, tzinfo=utc)),
        ),
    ]
