# Generated by Django 4.0.3 on 2024-01-11 16:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_alter_contact_created_alter_rate_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='body',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='headline',
            new_name='project_name',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='active',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_url',
            field=models.URLField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 16, 23, 51, 174557, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rate',
            name='created',
            field=models.TimeField(default=datetime.datetime(2024, 1, 11, 16, 23, 51, 179559, tzinfo=utc)),
        ),
    ]
