# Generated by Django 4.0.3 on 2024-01-15 10:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_alter_contact_created_alter_rate_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 10, 33, 39, 444083, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rate',
            name='created',
            field=models.TimeField(default=datetime.datetime(2024, 1, 15, 10, 33, 39, 454099, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='resume',
            name='response',
        ),
        migrations.AddField(
            model_name='resume',
            name='response',
            field=models.ManyToManyField(null=True, to='portfolio_app.resume_responsibility'),
        ),
    ]
