# Generated by Django 4.0.3 on 2024-01-15 17:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0008_skills_aria_level_alter_contact_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='resume',
            name='created',
            field=models.TimeField(default=datetime.datetime(2024, 1, 15, 17, 9, 19, 177350, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 17, 9, 19, 173352, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rate',
            name='created',
            field=models.TimeField(default=datetime.datetime(2024, 1, 15, 17, 9, 19, 178349, tzinfo=utc)),
        ),
    ]
