# Generated by Django 4.0.3 on 2024-01-15 18:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0009_alter_resume_options_resume_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 18, 59, 36, 873184, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rate',
            name='created',
            field=models.TimeField(default=datetime.datetime(2024, 1, 15, 18, 59, 36, 877182, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rate',
            name='image',
            field=models.ImageField(blank=True, default='avatar/avatar.svg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='rate',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='created',
            field=models.TimeField(default=datetime.datetime(2024, 1, 15, 18, 59, 36, 876183, tzinfo=utc)),
        ),
    ]
