# Generated by Django 4.0.3 on 2024-01-16 08:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0011_alter_contact_created_alter_rate_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='host',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='rating',
            new_name='review',
        ),
        migrations.AlterField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 8, 58, 59, 88856, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rate',
            name='created',
            field=models.TimeField(default=datetime.datetime(2024, 1, 16, 8, 58, 59, 104484, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rate',
            name='image',
            field=models.ImageField(blank=True, default='../static/assets/img/avatar/avatar.svg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='rate',
            name='occupation',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='created',
            field=models.TimeField(default=datetime.datetime(2024, 1, 16, 8, 58, 59, 104484, tzinfo=utc)),
        ),
    ]
