# Generated by Django 3.2.1 on 2024-01-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0013_auto_20240127_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume_details',
            name='cv',
        ),
        migrations.AddField(
            model_name='resume_details',
            name='cv_field',
            field=models.FileField(null=True, upload_to='cv_download'),
        ),
    ]
